### ISSUE TITLE
Response body with `{` in field of type string is incorrectly interpreted as object

### ISSUE THREAD

**Issue by klubi** [spring-cloud/spring-cloud-contract#1266]
When I define contract like this:

```java
Contract.make {
      name 'Some name'
      request {
        method 'POST'
        url '/aaa'
        body([
            "field": "value"
        ])
        headers {
          contentType(applicationJson())
        }
      }
      response {
        status OK()
        body([
            "field": "value",
            "otherField"        : "{\"aa\":\"bb\", \"cc\", \"dd\"}",
        ])
        headers {
          contentType(applicationJson())
        }
      }
    }
```

I'd expect value of "otherField" to be of type string in mapping.
It turns it's not.
Mapping in this case looks like this:
```json
"response" : {
    "status" : 200,
    "body" : "{\"otherField\":{\"aa\":\"bb\",\"cc\":\"dd\"}, \"field\", \"value\"}",
    "headers" : {
      "Content-Type" : "application/json"
    },
    "transformers" : [ "response-template" ]
  },
```
instead of 
```json
body: "{\"otherField\":\"{\"aa\":\"bb\",\"cc\":\"dd\"}\", \"field\", \"value\"}"
```

This causes deserialisation issues on client side, because client expects otherField to be String, and Jackson finds START_OBJECT, and throws:
```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: (PushbackInputStream); line: 1, column: 18] (through reference chain: a.b.c.Response["otherField"])
```

I see this for version 2.1.0, I was not able to check version 2.1.4.

**Comment by marcingrzejszczak** [comment]
Please check the latest version before filing an issue. If the issue got already fixed in 2.1.4 why do you even file this issue? I'm closing this until you verify against the latest released version.

**Comment by klubi** [comment]
I was able to verify that issue is still present on 2.1.4.
It seems to boil down to "if string starts with `{` the it's treated as object instead of string".

**Comment by marcingrzejszczak** [comment]
Can you please create a small sample? 

Cause  maybe I'm wrong but with 2.1.4 I see in a test that I get a following mapping

```json
{
  "id" : "8267eee4-91f4-4a45-85aa-30d2b3fe6a7e",
  "request" : {
    "url" : "/aaa",
    "method" : "POST",
    "headers" : {
      "Content-Type" : {
        "matches" : "application/json.*"
      }
    },
    "bodyPatterns" : [ {
      "matchesJsonPath" : "$[?(@.['field'] == 'value')]"
    } ]
  },
  "response" : {
    "status" : 200,
    "body" : "{\"field\":\"value\",\"otherField\":\"{\\\"aa\\\":\\\"bb\\\", \\\"cc\\\", \\\"dd\\\"}\"}",
    "headers" : {
      "Content-Type" : "application/json"
    },
    "transformers" : [ "response-template", "foo-transformer" ]
  },
  "uuid" : "8267eee4-91f4-4a45-85aa-30d2b3fe6a7e"
}
```

it seems to be correct?

**Comment by klubi** [comment]
sure, try this -> [SCC-SAMPLE](https://github.com/klubi/scc-sample)

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
