### ISSUE TITLE
baseClassMappings doesn't work as documented

### ISSUE THREAD

**Issue by jakub-bochenski** [spring-cloud/spring-cloud-contract#1930]
**Describe the bug**
Per docs this
```
    baseClassMapping('.*/com/.*', 'com.example.ComBase')
```
Should match to a contract inside `src/test/resources/contract/com/`

But it doesn't.

**Sample**
As seen in debug output the package will be just `com`. It will not match anything with a `/`

```
org.springframework.cloud.contract.verifier.builder.BaseClassProvider - Matching pattern for contract package [com] with setup {.*com.*=com.example.admin.TykContractBase} is [Optional[.*com.*=com.example.admin.TykContractBase]]
```

**Comment by marcingrzejszczak** [comment]
According to the regex101 your pattern indeed won't match https://regex101.com/r/bbXAaE/1

Instead, your pattern should look like this https://regex101.com/r/pKunCn/1 (`.*\/com\/.*` - with escaped slashes)

**Comment by marcingrzejszczak** [comment]
> Well, it's not "my" pattern, it comes from the SCC documentation.

oops... thanks for mentioning that then

> But then still, I think the value to be matched is just com, not /com/ according to the log quoted above

I'm still looking into that, maybe there's a bug somewhere

**Comment by marcingrzejszczak** [comment]
I don't see any such mention in our docs anymore so I guess this is fixed, or am I missing sth?

**Comment by jakub-bochenski** [comment]
I still see this in https://cloud.spring.io/spring-cloud-contract/reference/html/gradle-project.html#by-mapping

**Comment by marcingrzejszczak** [comment]
This is our old doc https://docs.spring.io/spring-cloud-contract/docs/current/reference/html/ and this is our new doc https://docs.spring.io/spring-cloud-contract/reference/

**Comment by jakub-bochenski** [comment]
> This is our old doc https://docs.spring.io/spring-cloud-contract/docs/current/reference/html/ and this is our new doc https://docs.spring.io/spring-cloud-contract/reference/

TIL... there is no indication in the docs itself that it's obsolete

In general trying to find the right docs for SCC is a real pain. 
Google mostly leads you to some obsolete 2.x docs, and even getting to those newer-obsolete docs requires some effort.

I'm not sure how much can be done... maybe you could just take down the old docs (or remove them from indexing with robots.txt etc) to avoid confusion?

**Comment by marcingrzejszczak** [comment]
The source of truth is here - https://spring.io/projects/spring-cloud-contract . We will look into doing sth about the old docs migration.

**Comment by marcingrzejszczak** [comment]
OK hopefully I fixed all the old docs to start pointing to the links to our new docs. Thanks again for pointing this out
