### ISSUE TITLE
Wiremock: Spring Context is always marked as dirty even when port is 0.

### ISSUE THREAD

**Issue by boothen** [spring-cloud/spring-cloud-contract#883]
With version 2.1.0.RELEASE the Spring context is always marked as dirty after each test run. This causes tests to run much slower as the Spring context is initialised each time.

The issue is in the following code in WireMockTestExecutionListener

```
	private boolean portIsFixed(TestContext testContext) {
		WireMockConfiguration wireMockProperties = wireMockConfig(testContext);
		int httpPort = wireMockProperties.wireMock.getServer().getPort();
		int httpsPort = wireMockProperties.wireMock.getServer().getHttpsPort();
		return (httpPort != 0 || httpsPort != -1) && httpsPort != 0;
	}
```

The httpPort is either set to a fixed value or given a dynamic value in WireMockApplicationListener. Therefore, httpPort can never be 0.

I've submitted a PR to workaround this issue, basically the code needs to determine if the port is dynamic based off the property value and not the httpPort value.

I've included a screenshot that runs the same test twice. The output from the 2nd test shows the "You've used fixed ports ..." warning message. 

<img width="1166" alt="screenshot 2019-02-13 at 23 07 50" src="https://user-images.githubusercontent.com/1582761/52750472-3cc36c80-2fe4-11e9-9e55-7815d65dc4a2.png">

**Comment by marcingrzejszczak** [comment]
Should be fixed via https://github.com/spring-cloud/spring-cloud-contract/commit/11965323ae947775927adb9564c072b4f848e28e

**Comment by boothen** [comment]
With 2.1.1.RELEASE I've noticed that the issue still occurs. The fix works for JUnit/SpringRunner tests. However, when using the framework with Cucumber it turns out that the context is refreshed multiple times.

On context initialisation the logic sets the portDynamic and httpsPortDynamic to true, but on subsequent refreshes the logic updates httpsPortDynamic to false.

I've submitted a Pull Request with the fix. However, I'm unable to provide a test to verify that the issue is fixed in the context refresh scenario.

**Comment by OlgaMaciaszek** [comment]
Reopening issue since PR was causing exceptions. Please provide a fixed PR.

**Comment by OlgaMaciaszek** [comment]
Reopening issue since PR was causing exceptions. Please provide a fixed PR.

**Comment by OlgaMaciaszek** [comment]
This should be fixed by https://github.com/spring-cloud/spring-cloud-contract/pull/1048
